# Generated by Django 4.1.2 on 2022-10-11 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_advocate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='advocate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.advocate'),
        ),
    ]
