# Generated by Django 4.1.2 on 2022-10-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_link_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='profile_image',
            field=models.ImageField(default='profile_image.png', upload_to='profile_images'),
        ),
    ]
