# Generated by Django 4.1.2 on 2022-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_advocate_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
