# Generated by Django 4.1.2 on 2022-11-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_links_github_alter_links_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
